// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2YyAOozNsbdosWCzHgslEu1pjiOGFvbE',
    appId: '1:465678927315:web:34c212693d8ea892321b26',
    messagingSenderId: '465678927315',
    projectId: 'to-do-list-b701d',
    authDomain: 'to-do-list-b701d.firebaseapp.com',
    databaseURL: 'https://to-do-list-b701d-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-b701d.appspot.com',
    measurementId: 'G-Z1KLN9P4N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD13A_Opuz2ChBCeRZF5P3JhS0APhQhkWs',
    appId: '1:465678927315:android:7ca0baf0eab9afae321b26',
    messagingSenderId: '465678927315',
    projectId: 'to-do-list-b701d',
    databaseURL: 'https://to-do-list-b701d-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-b701d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaSwT5L2I1qN8Fxw60nKBH_OIt9ZxYyKI',
    appId: '1:465678927315:ios:126428b529f5dd84321b26',
    messagingSenderId: '465678927315',
    projectId: 'to-do-list-b701d',
    databaseURL: 'https://to-do-list-b701d-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-b701d.appspot.com',
    iosBundleId: 'com.example.tdl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaSwT5L2I1qN8Fxw60nKBH_OIt9ZxYyKI',
    appId: '1:465678927315:ios:13e2aea6c6f172a9321b26',
    messagingSenderId: '465678927315',
    projectId: 'to-do-list-b701d',
    databaseURL: 'https://to-do-list-b701d-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-b701d.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2YyAOozNsbdosWCzHgslEu1pjiOGFvbE',
    appId: '1:465678927315:web:b2641de33a56347c321b26',
    messagingSenderId: '465678927315',
    projectId: 'to-do-list-b701d',
    authDomain: 'to-do-list-b701d.firebaseapp.com',
    databaseURL: 'https://to-do-list-b701d-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-b701d.appspot.com',
    measurementId: 'G-K415KSCFZD',
  );
}
